### ISSUE TITLE
Readme instructions does not work for mac users?

### ISSUE THREAD

**Issue by CandiaGu** [haoyuan96/RPCS_Dashboards#17]
I was installing the dependencies for repo (following the readme file), multiple pip installs failed because the requirements did not exist for pip.

I was just at this step
`pip3 install -r requirements.txt `

I am running python 3.7.4 on a mac.

**Comment by yitian9898** [comment]
Recommend checking if pip is installed properly on your local environment.

**Comment by litong-x** [comment]
What kind of packages did you fail to install? If it is psycopg2, please try pip3 install psycopg2-binary.
Or try to use the virtual environment and try the project.

**Comment by CandiaGu** [comment]
Thanks for the tips! Yeah I got it to work and can see the stuff :)
