### ISSUE TITLE
Can front end group remove not used html and use static in js/ css files?

### ISSUE THREAD

**Issue by Hanxi0124** [haoyuan96/RPCS_Dashboards#3]
Hi guys!

Since bootstrap templates contain too many pages, it's kind of confusing to understand which pages we are actually using. Can you remove not used ones?

Also, since we have a static file, can we use js/ css/ scss/ vendor from there instead of just getting online? I tried to modify css in patient parts, but I am not sure if you are going to use all the pages. It might be easier if you guys to modify it. Thanks!

**Comment by yitian9898** [comment]
- Removed unnecessary files in the caregiver template folder
- Moved common pages out of the caregiver template folder into the main template folder
